# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19D6yDNXXARVZrqyZy1ySCFzPbI-Cn-r-
"""

pip install opencv-python

from google.colab.patches import cv2_imshow
import cv2
rasm1=cv2.imread("rasm1.jpg")
rasm2=cv2.imread("rasm2.jpg")
rasm3=cv2.imread("rasm3.jpg")
rasm4=cv2.imread("rasm4.jpg")
rasm5=cv2.imread("rasm5.jpg")
cv2_imshow(rasm1)
cv2_imshow(rasm2)
cv2_imshow(rasm3)
cv2_imshow(rasm4)
cv2_imshow(rasm5)

oqqora=cv2.cvtColor(rasm1,cv2.COLOR_BGR2GRAY)
oqqoraa=cv2.cvtColor(rasm2,cv2.COLOR_BGR2GRAY)
oqqorab=cv2.cvtColor(rasm3,cv2.COLOR_BGR2GRAY)
oqqorac=cv2.cvtColor(rasm4,cv2.COLOR_BGR2GRAY)
oqqorad=cv2.cvtColor(rasm5,cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora)
cv2_imshow(oqqoraa)
cv2_imshow(oqqorab)
cv2_imshow(oqqorac)
cv2_imshow(oqqorad)